Script started on 2017年03月09日 (週四) 00時38分57秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
user.email=musicislife0503@gmail.com
user.name=shapeoflove
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/shapeoflove/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m  git clone https://github.com/<your github account>/l ab1.git
bash: your: No such file or directory
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m exit

Script done on 2017年03月09日 (週四) 00時39分45秒
